version: "2"

run:
  timeout: "15m"

linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
