services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d dev"]
      timeout: 30s
      interval: 5s
      retries: 3

  api:
    build: ./
    environment:
      DB_DSN: postgres://dev:dev@db:5432/dev?sslmode=disable
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
